#definiujemy tu klasy servisów aby móc ich następnie używać w services:  odc. 87
parameters:
    pipi_training.service.notification.class: PipiTrainingBundle\Service\NotificationService

services:
    pipi_notification:
        class: %pipi_training.service.notification.class%
        arguments: [@session]                         #sprawdzanie nazwy serwisu:   php app/console debug:container | grep session
#    pipi_training.example:
#        class: PipiTrainingBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
